def get_zaken_case_list():
    return [
        {
            "id": 3309,
            "address": {
                "bag_id": "0363010000746325",
                "id": 835,
                "full_address": "Mosplein 14, 1031AA",
                "street_name": "Mosplein",
                "number": 14,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1031AA",
                "lat": 52.3917152098767,
                "lng": 4.91299235984821,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0},
                    "case": 2,
                }
            ],
            "identification": "a9ab2268-652b-4994-8a2c-78c0941912d8",
            "start_date": "2021-02-26",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "e3d55ecd-7820-11eb-b73a-0242ac110025",
            "description": "aaa",
            "author": "6527e728-e850-4edb-a05e-2b836e43a8ef",
        },
        {
            "id": 3314,
            "address": {
                "bag_id": "0363010000874050",
                "id": 836,
                "full_address": "Wingerdweg 105-H, 1032AC",
                "street_name": "Wingerdweg",
                "number": 105,
                "suffix_letter": "",
                "suffix": "H",
                "postal_code": "1032AC",
                "lat": 52.3933589454374,
                "lng": 4.91724993689846,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.67},
                    "case": 2,
                }
            ],
            "identification": "83c12cda-230a-4b6b-930d-94027a8dbc73",
            "start_date": "2021-03-01",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "392d7fb9-7a74-11eb-8329-0242ac110015",
            "description": "asdfasdf",
            "author": "6527e728-e850-4edb-a05e-2b836e43a8ef",
        },
        {
            "id": 3318,
            "address": {
                "bag_id": "0363010000546385",
                "id": 837,
                "full_address": "Eerste Jan van der Heijdenstraat 10-B, 1072TT",
                "street_name": "Eerste Jan van der Heijdenstraat",
                "number": 10,
                "suffix_letter": "B",
                "suffix": "",
                "postal_code": "1072TT",
                "lat": 52.3527995440388,
                "lng": 4.88704678212924,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.12},
                    "case": 2,
                }
            ],
            "identification": "0f138a15-7c16-4de3-8ec4-f97d7fbd694f",
            "start_date": "2021-03-01",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "a1d7024f-7a8a-11eb-921c-0242ac110015",
            "description": "test3",
            "author": "5628b51c-98a0-4908-9afa-87d606b28590",
        },
        {
            "id": 3332,
            "address": {
                "bag_id": "0363010000746326",
                "id": 839,
                "full_address": "Mosplein 16, 1031AA",
                "street_name": "Mosplein",
                "number": 16,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1031AA",
                "lat": 52.3917874021452,
                "lng": 4.91306504139362,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 3,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.49},
                    "case": 2,
                }
            ],
            "identification": "8c953de5-c26b-41df-9ddc-44291ffa5944",
            "start_date": "2021-03-02",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "0a5d6b36-7b4b-11eb-9ec0-0242ac110015",
            "description": "dafsdf",
            "author": "6527e728-e850-4edb-a05e-2b836e43a8ef",
        },
        {
            "id": 3331,
            "address": {
                "bag_id": "0363010000783932",
                "id": 838,
                "full_address": "Prinsengracht 142, 1015EB",
                "street_name": "Prinsengracht",
                "number": 142,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1015EB",
                "lat": 52.3756314999135,
                "lng": 4.88354385024208,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.33},
                    "case": 2,
                }
            ],
            "identification": "c0c63ed1-c1be-448c-acab-212e6659020c",
            "start_date": "2021-03-02",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "d5ec65fb-7b33-11eb-a44a-0242ac11001d",
            "description": "test case",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3335,
            "address": {
                "bag_id": "0363010000783938",
                "id": 809,
                "full_address": "Prinsengracht 146-H, 1015EB",
                "street_name": "Prinsengracht",
                "number": 146,
                "suffix_letter": "",
                "suffix": "H",
                "postal_code": "1015EB",
                "lat": 52.3755592893845,
                "lng": 4.88347124322997,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.72},
                    "case": 2,
                }
            ],
            "identification": "efec1d99-c4ea-4c29-acd8-222f26ce5c1f",
            "start_date": "2021-03-03",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "929c73bc-7bf6-11eb-be8b-0242ac110008",
            "description": "test",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3340,
            "address": {
                "bag_id": "0363020001023315",
                "id": 829,
                "full_address": "Prinsengracht 146-G, 1015EB",
                "street_name": "Prinsengracht",
                "number": 146,
                "suffix_letter": "G",
                "suffix": "",
                "postal_code": "1015EB",
                "lat": 52.3754961641728,
                "lng": 4.88368966161857,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.01},
                    "case": 2,
                }
            ],
            "identification": "6473a4e4-62c7-4113-a751-5235963ba82e",
            "start_date": "2021-03-03",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "8490c1f3-7c4c-11eb-ab3e-0242ac110038",
            "description": "adas",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3351,
            "address": {
                "bag_id": "0363010000783911",
                "id": 841,
                "full_address": "Prinsengracht 130-1, 1015EB",
                "street_name": "Prinsengracht",
                "number": 130,
                "suffix_letter": "",
                "suffix": "1",
                "postal_code": "1015EB",
                "lat": 52.3758931300363,
                "lng": 4.88377584742741,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.23},
                    "case": 2,
                }
            ],
            "identification": "b2917530-1b71-4ad0-8c1a-ec3b3a02b0f6",
            "start_date": "2021-03-10",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "6bb5be04-87c2-11eb-8b51-0242ac110026",
            "description": "test zaak legalisatie",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3371,
            "address": {
                "bag_id": "0363010001172732",
                "id": 844,
                "full_address": "Prinsengracht 130-A, 1015EB",
                "street_name": "Prinsengracht",
                "number": 130,
                "suffix_letter": "A",
                "suffix": "",
                "postal_code": "1015EB",
                "lat": 52.3758390190816,
                "lng": 4.8837324051336,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.64},
                    "case": 2,
                }
            ],
            "identification": "d75a9888-7130-4494-b21c-431dd388f54e",
            "start_date": "2021-03-11",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "401fd335-8264-11eb-b9fc-0242ac110043",
            "description": "Toeristen gesignaleerd",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3376,
            "address": {
                "bag_id": "0363010000639161",
                "id": 845,
                "full_address": "Eerste Jan van der Heijdenstraat 18-H, 1072TT",
                "street_name": "Eerste Jan van der Heijdenstraat",
                "number": 18,
                "suffix_letter": "",
                "suffix": "H",
                "postal_code": "1072TT",
                "lat": 52.352818076763,
                "lng": 4.88717867414088,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.47},
                    "case": 2,
                }
            ],
            "identification": "b87f7c26-87a9-41bc-a664-12eb3342c6a2",
            "start_date": "2021-03-11",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "d76639e5-8274-11eb-b9fc-0242ac110043",
            "description": "De aanleiding",
            "author": "5628b51c-98a0-4908-9afa-87d606b28590",
        },
        {
            "id": 3368,
            "address": {
                "bag_id": "0363010000783913",
                "id": 842,
                "full_address": "Prinsengracht 130-3, 1015EB",
                "street_name": "Prinsengracht",
                "number": 130,
                "suffix_letter": "",
                "suffix": "3",
                "postal_code": "1015EB",
                "lat": 52.3758931300363,
                "lng": 4.88377584742741,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.74},
                    "case": 2,
                }
            ],
            "identification": "cf1b8e36-0c3b-4910-9e7d-94f757b809d4",
            "start_date": "2021-03-11",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "95879453-825a-11eb-8134-0242ac110003",
            "description": "Zaak 11 maart 12:05",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3370,
            "address": {
                "bag_id": "0363010000783912",
                "id": 843,
                "full_address": "Prinsengracht 130-2, 1015EB",
                "street_name": "Prinsengracht",
                "number": 130,
                "suffix_letter": "",
                "suffix": "2",
                "postal_code": "1015EB",
                "lat": 52.3758931300363,
                "lng": 4.88377584742741,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.63},
                    "case": 2,
                }
            ],
            "identification": "4f0a8d45-b770-4f6c-9de4-0db3ba7117ba",
            "start_date": "2021-03-11",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "e3be4c6a-8261-11eb-8134-0242ac110003",
            "description": "zaak 11 maart 13:00",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3382,
            "address": {
                "bag_id": "0363010012086329",
                "id": 840,
                "full_address": "Jodenbreestraat 25, 1011NH",
                "street_name": "Jodenbreestraat",
                "number": 25,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1011NH",
                "lat": 52.368696997753,
                "lng": 4.90391465857464,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.86},
                    "case": 2,
                }
            ],
            "identification": "4b451e0d-b1b4-4ba1-9ce1-ac14f481c53c",
            "start_date": "2021-03-11",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "d736dc32-82aa-11eb-b9fc-0242ac110043",
            "description": "htdfh",
            "author": "ce170864-3457-411c-85d4-5fd0c7be5c67",
        },
        {
            "id": 3385,
            "address": {
                "bag_id": "0363010000874053",
                "id": 804,
                "full_address": "Wingerdweg 107-1, 1032AC",
                "street_name": "Wingerdweg",
                "number": 107,
                "suffix_letter": "",
                "suffix": "1",
                "postal_code": "1032AC",
                "lat": 52.3934309602379,
                "lng": 4.91727855604405,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.23},
                    "case": 2,
                }
            ],
            "identification": "f06f7ca8-ac04-424a-acd3-da621ef405b1",
            "start_date": "2021-03-15",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "aa9d19b6-8675-11eb-beb5-0242ac110025",
            "description": "gg",
            "author": "6527e728-e850-4edb-a05e-2b836e43a8ef",
        },
        {
            "id": 3392,
            "address": {
                "bag_id": "0363010000783940",
                "id": 808,
                "full_address": "Prinsengracht 146-2, 1015EB",
                "street_name": "Prinsengracht",
                "number": 146,
                "suffix_letter": "",
                "suffix": "2",
                "postal_code": "1015EB",
                "lat": 52.3755592893845,
                "lng": 4.88347124322997,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.25},
                    "case": 2,
                }
            ],
            "identification": "d0040a2d-05bd-455a-94ab-adeae9825711",
            "start_date": "2021-03-16",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "7d76a768-8647-11eb-80d2-0242ac110025",
            "description": "test 16 maart 12:00",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3401,
            "address": {
                "bag_id": "0363010000783926",
                "id": 848,
                "full_address": "Prinsengracht 136-3, 1015EB",
                "street_name": "Prinsengracht",
                "number": 136,
                "suffix_letter": "",
                "suffix": "3",
                "postal_code": "1015EB",
                "lat": 52.375739784398,
                "lng": 4.88364541882545,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.24},
                    "case": 2,
                }
            ],
            "identification": "8e0dfaff-8bb0-413e-a191-865bdaf63495",
            "start_date": "2021-03-18",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "93d0e84b-87ee-11eb-a122-0242ac110026",
            "description": "Advertentie gezien op Airbnb, en melder vermoed hotelmatig gebruik van woning\n(18 maart 14:35)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3402,
            "address": {
                "bag_id": "0363020001023314",
                "id": 849,
                "full_address": "Prinsengracht 136-G, 1015EB",
                "street_name": "Prinsengracht",
                "number": 136,
                "suffix_letter": "G",
                "suffix": "",
                "postal_code": "1015EB",
                "lat": 52.3756574183324,
                "lng": 4.88384075680884,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.74},
                    "case": 2,
                }
            ],
            "identification": "db9156cf-77f6-4829-9728-68ec4174e11e",
            "start_date": "2021-03-18",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "c90c8861-87ee-11eb-a122-0242ac110026",
            "description": "vermoede van vakantieverhuur door collega toezichthouder",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3403,
            "address": {
                "bag_id": "0363010000546387",
                "id": 831,
                "full_address": "Eerste Jan van der Heijdenstraat 10-C, 1072TT",
                "street_name": "Eerste Jan van der Heijdenstraat",
                "number": 10,
                "suffix_letter": "C",
                "suffix": "",
                "postal_code": "1072TT",
                "lat": 52.3528175186793,
                "lng": 4.88704657956806,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.63},
                    "case": 2,
                }
            ],
            "identification": "d09aac2b-4c84-4dfb-b8db-ca2fda621066",
            "start_date": "2021-03-18",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "ee34723f-87ef-11eb-af16-0242ac110031",
            "description": "RH, 14:41",
            "author": "5628b51c-98a0-4908-9afa-87d606b28590",
        },
        {
            "id": 3405,
            "address": {
                "bag_id": "0363010012150033",
                "id": 850,
                "full_address": "Waterlooplein 22, 1011PG",
                "street_name": "Waterlooplein",
                "number": 22,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1011PG",
                "lat": 52.3675578073953,
                "lng": 4.90188271794319,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.74},
                    "case": 2,
                }
            ],
            "identification": "f84c34df-7c57-4d22-ac1c-126f07084682",
            "start_date": "2021-03-18",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "0b585b63-87f1-11eb-a122-0242ac110026",
            "description": "Afgelopen vrijdag en zaterdag toeristen gesignaleerd door buurtbewoner\n(18 mrt 14:51)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3406,
            "address": {
                "bag_id": "0363010000705974",
                "id": 851,
                "full_address": "Kinkerstraat 233-A, 1053EP",
                "street_name": "Kinkerstraat",
                "number": 233,
                "suffix_letter": "A",
                "suffix": "",
                "postal_code": "1053EP",
                "lat": 52.3652702469156,
                "lng": 4.86523556090375,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.32},
                    "case": 2,
                }
            ],
            "identification": "2b1da1c5-5af5-4adb-8b09-37b04cfb2b52",
            "start_date": "2021-03-18",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "3695d8ae-87f1-11eb-af16-0242ac110031",
            "description": "Vermoede van vakantieverhuur\n(18 mrt 14:52)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3407,
            "address": {
                "bag_id": "0363010000944251",
                "id": 852,
                "full_address": "Beukenplein 2-B, 1091KG",
                "street_name": "Beukenplein",
                "number": 2,
                "suffix_letter": "B",
                "suffix": "",
                "postal_code": "1091KG",
                "lat": 52.3575263579228,
                "lng": 4.9175854124911,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.43},
                    "case": 2,
                }
            ],
            "identification": "3e9c3fb5-54cc-4731-a4b9-b41da15d4134",
            "start_date": "2021-03-18",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "7df7ecce-87f1-11eb-af16-0242ac110031",
            "description": "Illegaal vakantieverhuur door verhuurders",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3409,
            "address": {
                "bag_id": "0363010000569397",
                "id": 854,
                "full_address": "Andreas Bonnstraat 40-3, 1091BA",
                "street_name": "Andreas Bonnstraat",
                "number": 40,
                "suffix_letter": "",
                "suffix": "3",
                "postal_code": "1091BA",
                "lat": 52.3592646851186,
                "lng": 4.91399978096631,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.32},
                    "case": 2,
                }
            ],
            "identification": "32cb36ad-abd7-4989-bba9-ec4266713d22",
            "start_date": "2021-03-18",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "c07a98c3-87f1-11eb-a122-0242ac110026",
            "description": "Vermoedde onrechtmatige bewoning door toeristen \n(18 mrt 14:56)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3410,
            "address": {
                "bag_id": "0363010001012440",
                "id": 855,
                "full_address": "Distelplein 15, 1031XH",
                "street_name": "Distelplein",
                "number": 15,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1031XH",
                "lat": 52.3916091535947,
                "lng": 4.90896824339727,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.68},
                    "case": 2,
                }
            ],
            "identification": "02aba042-1fe6-4deb-8941-ae2b7615493a",
            "start_date": "2021-03-18",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "e8d25b13-87f1-11eb-a122-0242ac110026",
            "description": "Toeristen gesignaleerd, meerdere keren deze maand\n(18 mrt 14:57)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3411,
            "address": {
                "bag_id": "0363010001036407",
                "id": 856,
                "full_address": "Klaprozenweg 25-B, 1032KK",
                "street_name": "Klaprozenweg",
                "number": 25,
                "suffix_letter": "B",
                "suffix": "",
                "postal_code": "1032KK",
                "lat": 52.3971041082224,
                "lng": 4.90983458671976,
            },
            "case_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2479,
                    "case": 3321,
                    "status_name": "Nog niet gelopen",
                    "status": 2,
                    "start_date": "2021-02-27",
                    "end_date": "null",
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.43},
                    "case": 2,
                }
            ],
            "identification": "60ddc874-0985-4b30-b5c0-8ea4022e29c0",
            "start_date": "2021-03-18",
            "end_date": "null",
            "is_legacy_bwv": False,
            "camunda_id": "173226d3-87f2-11eb-a122-0242ac110026",
            "description": "Toeristische vakantieverhuur vermoed door buurman.\n(18 mrt 14:58)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3418,
            "address": {
                "bag_id": "0363010000776470",
                "id": 863,
                "full_address": "Eerste Van Swindenstraat 42, 1093GE",
                "street_name": "Eerste Van Swindenstraat",
                "number": 42,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1093GE",
                "lat": 52.3622704545024,
                "lng": 4.92637314533082,
            },
            "case_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.29},
                    "case": 2,
                }
            ],
            "identification": "495c9ea7-b246-434b-b41a-d1b610d9057d",
            "start_date": "2021-03-18",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "8b8a11ae-87f9-11eb-af16-0242ac110031",
            "description": "net als bij buren, ook hier veel toeristen\n(18 mrt 15:52)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3419,
            "address": {
                "bag_id": "0363010000602270",
                "id": 864,
                "full_address": "Ceintuurbaan 7-2, 1072ER",
                "street_name": "Ceintuurbaan",
                "number": 7,
                "suffix_letter": "",
                "suffix": "2",
                "postal_code": "1072ER",
                "lat": 52.3524407952839,
                "lng": 4.88722695791296,
            },
            "case_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.32},
                    "case": 2,
                }
            ],
            "identification": "65bbc677-57f8-44e0-a0b8-7ab93e494f6b",
            "start_date": "2021-03-18",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "abaa8e7e-87f9-11eb-af16-0242ac110031",
            "description": "vooral in het weekend regelmatig toeristen hoorbaar\n(18 mrt 15:53)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3399,
            "address": {
                "bag_id": "0363010000783924",
                "id": 846,
                "full_address": "Prinsengracht 136-1, 1015EB",
                "street_name": "Prinsengracht",
                "number": 136,
                "suffix_letter": "",
                "suffix": "1",
                "postal_code": "1015EB",
                "lat": 52.375739784398,
                "lng": 4.88364541882545,
            },
            "case_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.93},
                    "case": 2,
                }
            ],
            "identification": "2f30c3d3-923f-487c-8834-c1023a097d3c",
            "start_date": "2021-03-18",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "63f9b502-87ed-11eb-af16-0242ac110031",
            "description": "Toeristen gesignaleerd door de buren\n\n(18maart 14:25)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3400,
            "address": {
                "bag_id": "0363010000783925",
                "id": 847,
                "full_address": "Prinsengracht 136-2, 1015EB",
                "street_name": "Prinsengracht",
                "number": 136,
                "suffix_letter": "",
                "suffix": "2",
                "postal_code": "1015EB",
                "lat": 52.375739784398,
                "lng": 4.88364541882545,
            },
            "case_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.34},
                    "case": 2,
                }
            ],
            "identification": "4d51cbd5-b4a8-4bce-9d94-a4564a4b8021",
            "start_date": "2021-03-18",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "0f51d7ec-87ee-11eb-af16-0242ac110031",
            "description": "Toeristen gezien in verschillende weekenden\n(18 maart 14:30)",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3436,
            "address": {
                "bag_id": "0363010012143319",
                "id": 834,
                "full_address": "Amstel 1, 1011PN",
                "street_name": "Amstel",
                "number": 1,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1011PN",
                "lat": 52.3676456031467,
                "lng": 4.90016547413043,
            },
            "case_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2495,
                    "case": 3436,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-22",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.13},
                    "case": 2,
                }
            ],
            "identification": "7c0d7e11-563a-4601-89b2-8cb910832c25",
            "start_date": "2021-03-22",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "1aa83e99-8afb-11eb-9434-0242ac110026",
            "description": "fafssfafsafsafs",
            "author": "76397eac-c186-4a04-bcb2-e905fbe9fa4b",
        },
        {
            "id": 3437,
            "address": {
                "bag_id": "0363010000783917",
                "id": 865,
                "full_address": "Prinsengracht 134-2, 1015EB",
                "street_name": "Prinsengracht",
                "number": 134,
                "suffix_letter": "",
                "suffix": "2",
                "postal_code": "1015EB",
                "lat": 52.3757848456662,
                "lng": 4.88367427817512,
            },
            "case_states": [
                {
                    "id": 2503,
                    "case": 3453,
                    "status_name": "Debrief",
                    "status": 7,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2502,
                    "case": 3453,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2501,
                    "case": 3453,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
            ],
            "current_states": [
                {
                    "id": 2503,
                    "case": 3453,
                    "status_name": "Debrief",
                    "status": 7,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2502,
                    "case": 3453,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2501,
                    "case": 3453,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.62},
                    "case": 2,
                }
            ],
            "identification": "f5396d51-14bb-4241-a7a7-a9579e05dd74",
            "start_date": "2021-03-22",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "db4d00e9-8b0b-11eb-b08e-0242ac110031",
            "description": "zaak 22 maart 13:40",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3453,
            "address": {
                "bag_id": "0363010000546384",
                "id": 830,
                "full_address": "Eerste Jan van der Heijdenstraat 10-A, 1072TT",
                "street_name": "Eerste Jan van der Heijdenstraat",
                "number": 10,
                "suffix_letter": "A",
                "suffix": "",
                "postal_code": "1072TT",
                "lat": 52.3527726440942,
                "lng": 4.88706176313037,
            },
            "case_states": [
                {
                    "id": 2503,
                    "case": 3453,
                    "status_name": "Debrief",
                    "status": 7,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2502,
                    "case": 3453,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2501,
                    "case": 3453,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
            ],
            "current_states": [
                {
                    "id": 2503,
                    "case": 3453,
                    "status_name": "Debrief",
                    "status": 7,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2502,
                    "case": 3453,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2501,
                    "case": 3453,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.75},
                    "case": 2,
                }
            ],
            "identification": "c4fc9b58-7c97-4668-816b-99daae75658c",
            "start_date": "2021-03-23",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "2c345ee0-8bf5-11eb-a363-0242ac110031",
            "description": "Test flow, 17:25",
            "author": "5628b51c-98a0-4908-9afa-87d606b28590",
        },
        {
            "id": 3457,
            "address": {
                "bag_id": "0363010000864314",
                "id": 806,
                "full_address": "Weesperstraat 113, 1018VN",
                "street_name": "Weesperstraat",
                "number": 113,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1018VN",
                "lat": 52.3630661025293,
                "lng": 4.90720586794304,
            },
            "case_states": [
                {
                    "id": 2509,
                    "case": 3457,
                    "status_name": "Aanschrijvingen",
                    "status": 8,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2508,
                    "case": 3457,
                    "status_name": "Debrief",
                    "status": 7,
                    "start_date": "2021-03-23",
                    "end_date": "2021-03-23",
                    "users": [],
                },
                {
                    "id": 2507,
                    "case": 3457,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": "2021-03-23",
                    "users": [],
                },
            ],
            "current_states": [
                {
                    "id": 2509,
                    "case": 3457,
                    "status_name": "Aanschrijvingen",
                    "status": 8,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.45},
                    "case": 2,
                }
            ],
            "identification": "abae018a-74e0-4ec9-b6ef-abd0f1ecd370",
            "start_date": "2021-03-23",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "e9c08557-8c07-11eb-926e-0242ac110026",
            "description": "Hoi",
            "author": "f7900505-0a75-4337-943a-44a7743e65ed",
        },
        {
            "id": 3460,
            "address": {
                "bag_id": "0363010000783943",
                "id": 866,
                "full_address": "Prinsengracht 148-2, 1015EB",
                "street_name": "Prinsengracht",
                "number": 148,
                "suffix_letter": "",
                "suffix": "2",
                "postal_code": "1015EB",
                "lat": 52.3755141655903,
                "lng": 4.88342769955242,
            },
            "case_states": [
                {
                    "id": 2527,
                    "case": 3482,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-25",
                    "end_date": None,
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2527,
                    "case": 3482,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-25",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.85},
                    "case": 2,
                }
            ],
            "identification": "b7b32e65-aaba-4661-934e-521fdb8b132e",
            "start_date": "2021-03-24",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "bee49e89-8c78-11eb-ae80-0242ac11000d",
            "description": "24 maart 09:05",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
        {
            "id": 3482,
            "address": {
                "bag_id": "0363010000874052",
                "id": 805,
                "full_address": "Wingerdweg 107-H, 1032AC",
                "street_name": "Wingerdweg",
                "number": 107,
                "suffix_letter": "",
                "suffix": "H",
                "postal_code": "1032AC",
                "lat": 52.3934309602379,
                "lng": 4.91727855604405,
            },
            "case_states": [
                {
                    "id": 2527,
                    "case": 3482,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-25",
                    "end_date": None,
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2527,
                    "case": 3482,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-25",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.54},
                    "case": 2,
                }
            ],
            "identification": "a251f329-02b8-4c97-adca-532233fc8223",
            "start_date": "2021-03-25",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "940fea2c-8d6b-11eb-9280-0242ac11002a",
            "description": "Dit is een zaak voor TOP",
            "author": "b925ba71-8738-4a38-8e64-63f8fa38444a",
        },
        {
            "id": 3481,
            "address": {
                "bag_id": "0363010012087407",
                "id": 867,
                "full_address": "Jodenbreestraat 19, 1011NH",
                "street_name": "Jodenbreestraat",
                "number": 19,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1011NH",
                "lat": 52.369089080317,
                "lng": 4.90308812550785,
            },
            "case_states": [
                {
                    "id": 2526,
                    "case": 3481,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-25",
                    "end_date": None,
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2526,
                    "case": 3481,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-25",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.33},
                    "case": 2,
                }
            ],
            "identification": "e087e7f3-7924-493c-a48d-e6a903348fe6",
            "start_date": "2021-03-25",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "44738342-8d6b-11eb-9280-0242ac11002a",
            "description": "16 toeristen",
            "author": "ce170864-3457-411c-85d4-5fd0c7be5c67",
        },
    ]


def get_zaken_case_search_result_list():
    return [
        {
            "id": 3457,
            "address": {
                "bag_id": "0363010000864314",
                "id": 806,
                "full_address": "Weesperstraat 113, 1018VN",
                "street_name": "Weesperstraat",
                "number": 113,
                "suffix_letter": "",
                "suffix": "",
                "postal_code": "1018VN",
                "lat": 52.3630661025293,
                "lng": 4.90720586794304,
            },
            "case_states": [
                {
                    "id": 2509,
                    "case": 3457,
                    "status_name": "Aanschrijvingen",
                    "status": 8,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                },
                {
                    "id": 2508,
                    "case": 3457,
                    "status_name": "Debrief",
                    "status": 7,
                    "start_date": "2021-03-23",
                    "end_date": "2021-03-23",
                    "users": [],
                },
                {
                    "id": 2507,
                    "case": 3457,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-23",
                    "end_date": "2021-03-23",
                    "users": [],
                },
            ],
            "current_states": [
                {
                    "id": 2509,
                    "case": 3457,
                    "status_name": "Aanschrijvingen",
                    "status": 8,
                    "start_date": "2021-03-23",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 2, "name": "Normaal", "weight": 0.20},
                    "case": 2,
                }
            ],
            "identification": "abae018a-74e0-4ec9-b6ef-abd0f1ecd370",
            "start_date": "2021-03-23",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "e9c08557-8c07-11eb-926e-0242ac110026",
            "description": "Hoi",
            "author": "f7900505-0a75-4337-943a-44a7743e65ed",
        },
        {
            "id": 3460,
            "address": {
                "bag_id": "0363010000783943",
                "id": 866,
                "full_address": "Prinsengracht 148-2, 1015EB",
                "street_name": "Prinsengracht",
                "number": 148,
                "suffix_letter": "",
                "suffix": "2",
                "postal_code": "1015EB",
                "lat": 52.3755141655903,
                "lng": 4.88342769955242,
            },
            "case_states": [
                {
                    "id": 2527,
                    "case": 3482,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-25",
                    "end_date": None,
                    "users": [],
                }
            ],
            "current_states": [
                {
                    "id": 2527,
                    "case": 3482,
                    "status_name": "Huisbezoek uitzetten",
                    "status": 6,
                    "start_date": "2021-03-25",
                    "end_date": None,
                    "users": [],
                }
            ],
            "team": {"id": 58, "name": "Vakantieverhuur"},
            "reason": {"id": 30, "name": "Melding", "team": 58},
            "schedules": [
                {
                    "id": 2,
                    "schedule_type": {"id": 2, "name": "Huisbezoek"},
                    "week_segment": {"id": 1, "name": "Weekend"},
                    "day_segment": {"id": 1, "name": "Avond"},
                    "priority": {"id": 1, "name": "Hoog", "weight": 0.87},
                    "case": 2,
                }
            ],
            "identification": "b7b32e65-aaba-4661-934e-521fdb8b132e",
            "start_date": "2021-03-24",
            "end_date": None,
            "is_legacy_bwv": False,
            "camunda_id": "bee49e89-8c78-11eb-ae80-0242ac11000d",
            "description": "24 maart 09:05",
            "author": "0299cfe1-76f3-4896-b065-cf15a44bb950",
        },
    ]
