# Generated by Django 3.1.2 on 2021-03-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0019_remove_teamsettings_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamsettings",
            name="fraud_predict",
        ),
        migrations.AddField(
            model_name="teamsettings",
            name="fraud_prediction_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ["vakantieverhuur", "vakantieverhuur"],
                    ["onderhuur", "onderhuur"],
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
