# Generated by Django 3.1.2 on 2021-03-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0020_auto_20210302_1249"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamsettings",
            options={"ordering": ["name"], "verbose_name_plural": "Team settings"},
        ),
    ]
