# Generated by Django 3.1.2 on 2021-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0021_auto_20210303_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsettings",
            name="use_zaken_backend",
            field=models.BooleanField(default=False),
        ),
    ]
