# Generated by Django 3.1.2 on 2021-03-23 09:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0023_teamsettings_zaken_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="daysettings",
            name="day_segments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="daysettings",
            name="priorities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="daysettings",
            name="week_segments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
