# Generated by Django 3.1.2 on 2021-03-26 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0025_auto_20210324_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="weights",
            name="reason",
            field=models.FloatField(
                default=0.25,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="weights",
            name="state_types",
            field=models.FloatField(
                default=0.25,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
