# Generated by Django 3.1.2 on 2021-03-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0026_auto_20210326_2112"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postalcoderangeset",
            options={"ordering": ["name"]},
        ),
    ]
