# Generated by Django 3.1.2 on 2021-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0028_daysettings_week_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="daysettings",
            name="max_use_limit",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
