# Generated by Django 3.1.2 on 2021-04-19 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0029_daysettings_max_use_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="weights",
            name="priority",
            field=models.FloatField(
                default=0.3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
