# Generated by Django 3.1.2 on 2021-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0030_weights_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="daysettings",
            options={"ordering": ("name",), "verbose_name_plural": "Day settings"},
        ),
        migrations.AddField(
            model_name="teamsettings",
            name="top_cases_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Dit getal bepaald hoeveel van best matches zaken, gebruikt moeten worden als start punt. Als hier 0 gebruikt wordt, worden alle gevonden zaken gebruikt als start punt. Dit betekent dat 0 de langzaamste optie is voor het genereren van een looplijst.",
            ),
        ),
    ]
