# Generated by Django 3.1.2 on 2021-03-23 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0060_merge_20201130_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerarysettings",
            name="day_segments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="itinerarysettings",
            name="priorities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="itinerarysettings",
            name="week_segments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
