# Generated by Django 3.1.2 on 2021-03-24 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0061_auto_20210323_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerarysettings",
            name="reasons",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="itinerarysettings",
            name="state_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
