# Generated by Django 3.1.2 on 2021-03-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0062_auto_20210324_1423"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itineraryteammember",
            options={"ordering": ["id"]},
        ),
    ]
