# Generated by Django 3.2 on 2021-04-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_auto_20210318_1028"),
        ("itinerary", "0063_auto_20210330_1205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerarysettings",
            name="start_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cases.case",
            ),
        ),
    ]
