# Generated by Django 3.1.2 on 2021-03-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_stadiumlabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="is_legacy_bwv",
            field=models.BooleanField(default=True),
        ),
    ]
