# Generated by Django 3.1.2 on 2021-03-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_case_is_legacy_bwv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="is_legacy_bwv",
            new_name="is_top_bwv_case",
        ),
    ]
