# Generated by Django 3.1.2 on 2021-03-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0015_visitteammember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitmetadata",
            name="visit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta_data",
                to="visits.visit",
            ),
        ),
    ]
